version: "3.9"
services:
  envoy:
    build: ./config/envoy
    ports:
      - "${ENVOY_BACKEND_PORT}:${ENVOY_BACKEND_PORT}"
      - "${ENVOY_ADMIN_PORT}:${ENVOY_ADMIN_PORT}"
      - "${ENVOY_BACKEND_WS_PORT}:${ENVOY_BACKEND_WS_PORT}"
    environment:
      SERVICE_NAME: backend
      DEBUG_LEVEL: error
      SERVICE_PORT: "${NODE_PORT}"
      SERVICE_WS_PORT: "${NODE_WS_PORT}"
      SERVICE_LISTEN_PORT: "${ENVOY_BACKEND_PORT}"
      SERVICE_LISTEN_WS_PORT: "${ENVOY_BACKEND_WS_PORT}"
      ADMIN_LISTEN_PORT: "${ENVOY_ADMIN_PORT}"
    volumes:
      - ./config/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - dev_onboarding
    depends_on:
      - backend
  backend:
    image: dev_onboarding_backend
    build: ./
    command: npm run start
    expose:
      - "${NODE_PORT}"
      - "${NODE_WS_PORT}"
    restart: unless-stopped
    environment:
      NODE_PORT: "${NODE_PORT}"
      NODE_WS_PORT: "${NODE_WS_PORT}"
      # Postgres
      POSTGRES_URL: "${POSTGRES_URL}"
      # Redis
      REDIS_DB_HOST: redis
      REDIS_DB_PORT: 6379
      KAFKA_IP: ${HOST_IP}
    networks:
      - dev_onboarding
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    container_name: dev_onboarding_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgresDB:/var/lib/postgresql
    networks:
      - dev_onboarding
  redis:
    image: redis
    container_name: dev_onboarding_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - dev_onboarding
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - dev_onboarding
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - dev_onboarding

volumes:
  postgresDB:
  redis:


networks:
  dev_onboarding:
    driver: bridge
