name: CI/CD
on: 
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: cd backend 

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm run build --if-presetn

    - name: Build
      run: npm test
      
    - name: remove package-lock.json
      run: rm package-lock.json

    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: dev-onboarding-midient
        heroku_email: ${{secrets.HEROKU_EMAIL}}